# This file was generated by GoReleaser. DO NOT EDIT.
cask "qrev" do
  name "qrev"
  desc "qrev is a SQL execution history management tool."
  homepage "https://github.com/winebarrel/qrev"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qrev"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_darwin_amd64.tar.gz"
      sha256 "f1c0b09d5a917cfbbd170db5b46866551ef45652e8cc61256eab96369f4f0943"
    end
    on_arm do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_darwin_arm64.tar.gz"
      sha256 "70c7e92098d5a65801db2e70e764eae512c0a003453f41214f36d50a7cbf9d44"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_linux_amd64.tar.gz"
      sha256 "4a7fb24d6710097d596b750fe990262c028461e90d633e0deaa24054dec718c0"
    end
    on_arm do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_linux_arm64.tar.gz"
      sha256 "7f17ac5f3f6cd94260bebbf0dc9ae22c47f4ffc76e2185af7a909ea6e3f3a6ca"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qrev"]
    end
  end

  # No zap stanza required
end
