# This file was generated by GoReleaser. DO NOT EDIT.
cask "qrev" do
  name "qrev"
  desc "qrev is a SQL execution history management tool."
  homepage "https://github.com/winebarrel/qrev"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qrev"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_darwin_amd64.tar.gz"
      sha256 "59454a43a63af2c2bfec7d8fa7bd4420c8e54c7c2d793dafc0501aa44cc9312f"
    end
    on_arm do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_darwin_arm64.tar.gz"
      sha256 "404ea2d22e8b6b350927f420e747a07c45fb32608063ec748e969d2e3af6b86d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_linux_amd64.tar.gz"
      sha256 "c73466bc9f55056bc15a7a26c62aef681b5460b33b566fcab792a9372631d775"
    end
    on_arm do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_linux_arm64.tar.gz"
      sha256 "bdc3a6aa9cf97801cbe0153a720fc7ccb6f52883dbc78459994d12619f97dcaf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qrev"]
    end
  end

  # No zap stanza required
end
