# This file was generated by GoReleaser. DO NOT EDIT.
cask "qrev" do
  name "qrev"
  desc "qrev is a SQL execution history management tool."
  homepage "https://github.com/winebarrel/qrev"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qrev"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_darwin_amd64.tar.gz"
      sha256 "a4c35ccb3d7a5f29c9fa82a77d6a39df5bcb3db285502e621b24e3a973e4bd95"
    end
    on_arm do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_darwin_arm64.tar.gz"
      sha256 "fc1fc25f392d59c7f05b3d4148acd073eaf14128dd0b0ce14be9528b90768121"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_linux_amd64.tar.gz"
      sha256 "357cdf8c78d6ffe9b081c6118078be0471873a1dd265ee2aff6e36081e9770cf"
    end
    on_arm do
      url "https://github.com/winebarrel/qrev/releases/download/v#{version}/qrev_#{version}_linux_arm64.tar.gz"
      sha256 "8988f2c54e17fce8b338a80ade999060d825235e7cce2b48c024dce79ca4caff"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qrev"]
    end
  end

  # No zap stanza required
end
